"""empty message

Revision ID: c2036c6bfdbd
Revises: 11b62f8ced57
Create Date: 2019-09-30 13:17:47.217475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2036c6bfdbd'
down_revision = '11b62f8ced57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('party', sa.Column('party_code', sa.String(length=6), nullable=True))
    op.drop_column('user', 'profile_img')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_img', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('party', 'party_code')
    # ### end Alembic commands ###
